name: propertyhub-v1
region: nyc

# Static Site - Frontend (React/Vite)
static_sites:
  - name: frontend
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true
    
    # Source directory (root of repo)
    source_dir: /
    
    # Build configuration
    build_command: npm install && npm run build
    output_dir: dist
    
    # Environment variables for build
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}
    
    # Routes
    routes:
      - path: /

# Backend Service - Main API (Node.js/Express)
services:
  - name: backend
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: cd backend && npm ci && npx prisma generate && npm run build
    run_command: cd backend && node dist/index.js
    
    # Source directory
    source_dir: /
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xs
    
    # HTTP configuration
    http_port: 5000
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      # Add your other environment variables in DigitalOcean UI:
      # - DATABASE_URL
      # - JWT_SECRET
      # - FRONTEND_URL
      # - REDIS_URL (for verification queue)
      # - UPSTASH_REDIS_URL (for verification queue - alternative)
      # - DOJAH_API_KEY (for verification provider)
      # - DOJAH_APP_ID (for verification provider)
      # - DOJAH_WEBHOOK_SECRET (for verification webhooks)
      # - etc.

# Database
databases:
  - name: production-database
    engine: PG
    production: true
    version: "15"
