#!/bin/bash

# Simple script to get payment details using Prisma Studio or direct SQL
# Usage: bash scripts/get-payment-details-simple.sh [order_id]

ORDER_ID="${1:-PH-1765994852895-r6cbpt}"

echo "🔍 Payment Details for: $ORDER_ID"
echo "================================"
echo ""
echo "📋 Run this SQL query in Prisma Studio or your database:"
echo ""
echo "SELECT"
echo "  id,"
echo "  status,"
echo "  \"providerReference\","
echo "  \"customerId\","
echo "  \"tenantId\","
echo "  amount,"
echo "  currency,"
echo "  metadata->>'monicreditTransactionId' as transaction_id,"
echo "  metadata->>'webhookReceivedAt' as webhook_time,"
echo "  \"createdAt\","
echo "  \"updatedAt\""
echo "FROM payments"
echo "WHERE \"providerReference\" = '$ORDER_ID';"
echo ""
echo "📝 Or use Prisma Studio:"
echo "   npx prisma studio"
echo ""
echo "   Then navigate to 'payments' table and search for:"
echo "   providerReference = $ORDER_ID"
echo ""
echo "🔧 Once you have the customerId and transaction_id from Monicredit dashboard,"
echo "   run the test webhook:"
echo ""
echo "   bash scripts/test-webhook-for-payment.sh \\"
echo "     $ORDER_ID \\"
echo "     ACX_TRANSACTION_ID_FROM_MONICREDIT \\"
echo "     CUSTOMER_ID_FROM_DATABASE"
