# DigitalOcean App Platform Configuration
# This file defines your entire application infrastructure

name: contrezz-saas
region: nyc

# Database
databases:
  - name: contrezz-db
    engine: PG
    version: "15"
    production: true
    cluster_name: contrezz-db-cluster

# Backend Service
services:
  - name: backend
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME

    build_command: npm install && npm run build
    run_command: npm start

    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 5000

    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      # Server Configuration
      - key: NODE_ENV
        scope: RUN_TIME
        value: production

      - key: PORT
        scope: RUN_TIME
        value: "5000"

      # Database (auto-injected by DigitalOcean)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${contrezz-db.DATABASE_URL}

      # JWT Configuration (CHANGE THESE!)
      - key: JWT_SECRET
        scope: RUN_TIME
        value: CHANGE_ME_GENERATE_USING_NODE_CRYPTO
        type: SECRET

      - key: JWT_EXPIRES_IN
        scope: RUN_TIME
        value: 7d

      # CORS - Frontend URL (will be auto-updated after frontend deployment)
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${APP_URL}

      # File Upload
      - key: MAX_FILE_SIZE
        scope: RUN_TIME
        value: "5242880"

      - key: UPLOAD_DIR
        scope: RUN_TIME
        value: ./uploads

      # Payment Gateway - Platform Level (OPTIONAL)
      # Add these if you want to charge property owners for subscriptions
      # - key: PAYSTACK_SECRET_KEY
      #   scope: RUN_TIME
      #   value: sk_live_xxxxx
      #   type: SECRET

      # - key: PAYSTACK_PUBLIC_KEY
      #   scope: RUN_TIME
      #   value: pk_live_xxxxx

      # - key: PAYSTACK_TEST_SECRET_KEY
      #   scope: RUN_TIME
      #   value: sk_test_xxxxx
      #   type: SECRET

      # - key: PAYSTACK_TEST_PUBLIC_KEY
      #   scope: RUN_TIME
      #   value: pk_test_xxxxx

# Frontend Static Site
static_sites:
  - name: frontend
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME

    build_command: npm install && npm run build
    output_dir: dist

    environment_slug: node-js

    envs:
      # Backend API URL (auto-injected by DigitalOcean)
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${backend.PUBLIC_URL}

    routes:
      - path: /

    catchall_document: index.html

# Jobs (for database migrations - PRODUCTION SAFE)
jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME

    build_command: npm install
    # PRODUCTION SAFE: Uses migrations to preserve all data
    # NEVER use db push or seed in production!
    run_command: npx prisma generate && npx prisma migrate deploy

    environment_slug: node-js
    instance_size_slug: basic-xxs

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${contrezz-db.DATABASE_URL}

