name: propertyhub-v1
region: nyc

# Static Site - Frontend (React/Vite)
static_sites:
  - name: frontend
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: npm run build
    output_dir: dist
    
    # Environment variables for build
    envs:
      - key: NODE_ENV
        value: production
    
    # Routes
    routes:
      - path: /

# Backend Service - Main API (Node.js/Express)
services:
  - name: backend
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: cd backend && npm install && npm run build
    run_command: cd backend && node dist/server.js
    
    # Source directory
    source_dir: /
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xs
    
    # HTTP configuration
    http_port: 5000
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      # Add your other environment variables in DigitalOcean UI:
      # - DATABASE_URL
      # - JWT_SECRET
      # - FRONTEND_URL
      # - etc.

  - name: verification-service
    # CRITICAL: Force Dockerfile-based build
    dockerfile_path: verification-service/Dockerfile
    source_dir: /
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xs
    
    # HTTP configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"

# Database
databases:
  - name: production-database
    engine: PG
    production: true
    version: "15"
