name: contrezz-backend
region: nyc

services:
  - name: backend
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true

    source_dir: backend

    # Build command - generate Prisma Client during build phase
    build_command: npm ci && npm run build

    # Run command - start the application
    run_command: npm run start

    # Instance configuration
    instance_count: 1
    instance_size_slug: professional-xs

    # Environment variables
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PORT
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_USER
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PASS
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_FROM
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_ENDPOINT
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_BUCKET
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_REGION
        scope: RUN_TIME
        type: SECRET

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # HTTP configuration
    http_port: 5000

    # Routes
    routes:
      - path: /

databases:
  - name: contrezz-db-prod
    engine: PG
    production: true
    version: "15"
