name: propertyhub-v1-verification-serv
region: nyc

services:
  - name: verification-service
    # CRITICAL: Force Dockerfile-based build
    dockerfile_path: verification-service/Dockerfile
    source_dir: /
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true

    # Instance configuration
    instance_count: 2
    instance_size_slug: basic-xs

    # HTTP configuration
    http_port: 8080

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables (you'll add these in UI)
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"

# Database attachment (you'll configure this in UI)
databases:
  - name: production-database
    engine: PG
    production: true
