# DigitalOcean App Platform Configuration for Public Backend
# This file defines the deployment configuration for the public API

name: contrezz-public-api
region: nyc

# Public Backend API Service
services:
  - name: public-api
    environment_slug: node-js
    github:
      repo: oluwaseyiolukoya/propertyhub_v1
      branch: main
      deploy_on_push: true
    source_dir: /public-backend

    # Build configuration
    # TypeScript is in dependencies (not devDependencies) so it survives pruning
    build_command: npx prisma generate && npm run build
    run_command: npm start

    # Resource allocation
    instance_count: 1
    instance_size_slug: basic-xxs # $5/month - upgrade as needed

    # Environment variables
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "8080" # DigitalOcean uses 8080 internally
      - key: PUBLIC_DATABASE_URL
        type: SECRET
        # Value must be set in DigitalOcean console - never commit passwords
        # Get connection string from: doctl databases connection contrezz-public-db --format ConnectionString
      - key: ALLOWED_ORIGINS
        value: "https://contrezz.com,https://www.contrezz.com,https://admin.contrezz.com"
      - key: APP_URL
        value: "https://app.contrezz.com"
      - key: APP_SIGNUP_URL
        value: "https://app.contrezz.com/signup"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    # HTTP configuration
    http_port: 8080

    # Routes (custom domain)
    routes:
      - path: /

# Database for public content
# Note: Database already exists, will be linked manually after deployment
# databases:
#   - name: public-db
#     engine: PG
#     version: "15"
#     production: true
#     cluster_name: contrezz-public-db
#     db_name: contrezz_public
#     db_user: doadmin
#     size: db-s-1vcpu-1gb

# Optional: Static site for public frontend (if using separate frontend)
# static_sites:
#   - name: public-frontend
#     github:
#       repo: your-org/test_ui_figma_and_cursor
#       branch: main
#       deploy_on_push: true
#     source_dir: /public-frontend
#     build_command: npm install && npm run build
#     output_dir: /dist
#     routes:
#       - path: /

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
