name: contrezz-verification
region: nyc

services:
  # API Service - Handles HTTP requests
  - name: verification-api
    github:
      repo: YOUR_GITHUB_USERNAME/test_ui_figma_and_cursor
      branch: main
      deploy_on_push: true
    source_dir: /verification-service
    build_command: |
      npm ci
      npx prisma generate
      npm run build
    run_command: |
      npx prisma migrate deploy
      npm start
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 5001
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: PORT
        value: "5001"
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_APP_ID
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_BASE_URL
        value: "https://api.dojah.io"
      - key: SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_REGION
        value: "nyc3"
      - key: SPACES_BUCKET
        value: "contrezz-verification-docs"
      - key: SPACES_ENDPOINT
        value: "https://nyc3.digitaloceanspaces.com"
      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET
      - key: API_KEY_MAIN_DASHBOARD
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_ORIGINS
        value: "https://contrezz.com,https://api.contrezz.com"
      - key: MAIN_DASHBOARD_URL
        value: "https://api.contrezz.com"

  # Background Worker - Processes verification jobs
  - name: verification-worker
    github:
      repo: YOUR_GITHUB_USERNAME/test_ui_figma_and_cursor
      branch: main
      deploy_on_push: true
    source_dir: /verification-service
    build_command: |
      npm ci
      npx prisma generate
      npm run build
    run_command: npm run worker
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_APP_ID
        scope: RUN_TIME
        type: SECRET
      - key: DOJAH_BASE_URL
        value: "https://api.dojah.io"
      - key: SPACES_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_REGION
        value: "nyc3"
      - key: SPACES_BUCKET
        value: "contrezz-verification-docs"
      - key: SPACES_ENDPOINT
        value: "https://nyc3.digitaloceanspaces.com"
      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET

# Optional: Create managed databases
# Uncomment if you want DigitalOcean to manage these for you
# databases:
#   - name: verification-db
#     engine: PG
#     version: "15"
#     production: true
#     cluster_name: verification-db-prod
#
#   - name: verification-redis
#     engine: REDIS
#     version: "7"
#     production: true
