/**
 * Nigerian States and Major Cities
 * For use in location dropdowns
 */

export const NIGERIAN_STATES = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT (Abuja)',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
  'Others'
] as const;

export const NIGERIAN_CITIES = [
  // Major Cities
  'Lagos',
  'Abuja',
  'Kano',
  'Ibadan',
  'Port Harcourt',
  'Benin City',
  'Kaduna',
  'Enugu',
  'Aba',
  'Ilorin',
  'Jos',
  'Warri',
  'Calabar',
  'Onitsha',
  'Akure',
  'Abeokuta',
  'Owerri',
  'Uyo',
  'Maiduguri',
  'Zaria',
  'Sokoto',
  'Ado-Ekiti',
  'Osogbo',
  'Asaba',
  'Umuahia',
  'Bauchi',
  'Gombe',
  'Yola',
  'Makurdi',
  'Jalingo',
  'Lokoja',
  'Lafia',
  'Minna',
  'Dutse',
  'Katsina',
  'Damaturu',
  'Gusau',
  'Birnin Kebbi',
  'Abakaliki',
  'Yenagoa',
  'Ikeja',
  'Lekki',
  'Victoria Island',
  'Ikoyi',
  'Surulere',
  'Festac',
  'Ajah',
  'Ikotun',
  'Egbeda',
  'Agege',
  'Others'
] as const;

export const COUNTRIES = [
  'Nigeria',
  'United States',
  'United Kingdom',
  'Canada',
  'Ghana',
  'South Africa',
  'Kenya',
  'Abidjan, Côte d\'Ivoire',
  'United Arab Emirates',
  'Saudi Arabia',
  'Germany',
  'France',
  'China',
  'India',
  'Australia',
  'Brazil',
  'Others'
] as const;

// Côte d'Ivoire States/Regions
export const IVORY_COAST_REGIONS = [
  'Lagunes',
  'Haut-Sassandra',
  'Savanes',
  'Vallée du Bandama',
  'Moyen-Comoe',
  'Gbêkê',
  'Woroba',
  'Sud-Comoe',
  'Marahoué',
  'Fromager',
  'N\'zi-Comoe',
  'Mé',
  'Indénié-Djuablin',
  'Sud-Bandama',
  'Agnéby-Tiassa',
  'Gôh',
  'Lôh-Djiboua',
  'Gbôklé',
  'Cavally',
  'Guémon',
  'Tonkpi',
  'Bagoué',
  'Poro',
  'Tchologo',
  'Gboklè',
  'Bafing',
  'Worodougou',
  'Béré',
  'Iffou',
  'Moronou',
  'Nawa',
  'Others'
] as const;

// Côte d'Ivoire Cities
export const IVORY_COAST_CITIES = [
  'Abidjan',
  'Bouaké',
  'Daloa',
  'Yamoussoukro',
  'San-Pédro',
  'Korhogo',
  'Man',
  'Divo',
  'Gagnoa',
  'Abengourou',
  'Agboville',
  'Dabou',
  'Grand-Bassam',
  'Bondoukou',
  'Odienné',
  'Séguéla',
  'Katiola',
  'Bingerville',
  'Adzopé',
  'Issia',
  'Soubré',
  'Duékoué',
  'Danané',
  'Ferkessédougou',
  'Boundiali',
  'Oumé',
  'Toumodi',
  'Vavoua',
  'Zuenoula',
  'Tiassalé',
  'Others'
] as const;

export type NigerianState = typeof NIGERIAN_STATES[number];
export type NigerianCity = typeof NIGERIAN_CITIES[number];
export type Country = typeof COUNTRIES[number];
export type IvoryCoastRegion = typeof IVORY_COAST_REGIONS[number];
export type IvoryCoastCity = typeof IVORY_COAST_CITIES[number];

