# Digital Ocean App Platform Configuration
# This file defines how to deploy the Contrezz backend

name: contrezz-backend
region: nyc

# Backend service
services:
  - name: api
    # GitHub integration
    github:
      repo: YOUR_GITHUB_USERNAME/test_ui_figma_and_cursor
      branch: main
      deploy_on_push: true

    # Build configuration
    source_dir: /backend

    build_command: |
      npm ci
      npx prisma generate
      npm run build

    run_command: npm start

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $12/month (512MB RAM, 1 vCPU)

    # HTTP configuration
    http_port: 8080

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: "8080"

      # Database connection (will be set by Terraform or manually)
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET

      # JWT secret
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET

      # Paystack keys
      - key: PAYSTACK_SECRET_KEY
        value: ${PAYSTACK_SECRET_KEY}
        type: SECRET

      - key: PAYSTACK_PUBLIC_KEY
        value: ${PAYSTACK_PUBLIC_KEY}

      # Frontend URL (update after frontend deployment)
      - key: FRONTEND_URL
        value: https://contrezz.com

      - key: CORS_ORIGIN
        value: https://contrezz.com

    # Routes
    routes:
      - path: /api

# Database (managed separately via Terraform)
databases:
  - name: db
    engine: PG
    production: true
    version: "15"

# Domains (optional - configure after deployment)
# domains:
#   - domain: api.contrezz.com
#     type: PRIMARY

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

