-- Add missing storage-related tables
-- Generated by Prisma migrate diff and filtered to only create missing tables

-- CreateTable
CREATE TABLE IF NOT EXISTS "storage_usage" (
    "id" TEXT NOT NULL,
    "customer_id" TEXT NOT NULL,
    "file_type" TEXT NOT NULL,
    "category" TEXT,
    "file_count" INTEGER NOT NULL DEFAULT 0,
    "total_size" BIGINT NOT NULL DEFAULT 0,
    "last_updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "storage_usage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "storage_transactions" (
    "id" TEXT NOT NULL,
    "customer_id" TEXT NOT NULL,
    "file_id" TEXT,
    "file_path" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "file_size" BIGINT NOT NULL,
    "file_type" TEXT,
    "action" TEXT NOT NULL,
    "uploaded_by" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "storage_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "invoice_attachments" (
    "id" TEXT NOT NULL,
    "invoice_id" TEXT NOT NULL,
    "customer_id" TEXT NOT NULL,
    "file_path" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "file_size" BIGINT NOT NULL,
    "file_type" TEXT NOT NULL,
    "mime_type" TEXT NOT NULL,
    "uploaded_by" TEXT NOT NULL,
    "uploaded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "invoice_attachments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "storage_usage_customer_id_file_type_category_key" ON "storage_usage"("customer_id", "file_type", "category");
CREATE INDEX IF NOT EXISTS "storage_usage_customer_id_idx" ON "storage_usage"("customer_id");
CREATE INDEX IF NOT EXISTS "storage_usage_file_type_idx" ON "storage_usage"("file_type");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "storage_transactions_customer_id_idx" ON "storage_transactions"("customer_id");
CREATE INDEX IF NOT EXISTS "storage_transactions_created_at_idx" ON "storage_transactions"("created_at");
CREATE INDEX IF NOT EXISTS "storage_transactions_action_idx" ON "storage_transactions"("action");
CREATE INDEX IF NOT EXISTS "storage_transactions_file_path_idx" ON "storage_transactions"("file_path");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "invoice_attachments_invoice_id_idx" ON "invoice_attachments"("invoice_id");
CREATE INDEX IF NOT EXISTS "invoice_attachments_customer_id_idx" ON "invoice_attachments"("customer_id");
CREATE INDEX IF NOT EXISTS "invoice_attachments_uploaded_at_idx" ON "invoice_attachments"("uploaded_at" DESC);

-- AddForeignKey
ALTER TABLE "storage_usage" ADD CONSTRAINT "storage_usage_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "storage_transactions" ADD CONSTRAINT "storage_transactions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "invoice_attachments" ADD CONSTRAINT "invoice_attachments_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Add foreign keys for users if the columns exist
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'storage_transactions' AND column_name = 'uploaded_by') THEN
    ALTER TABLE "storage_transactions" DROP CONSTRAINT IF EXISTS "storage_transactions_uploaded_by_fkey";
    ALTER TABLE "storage_transactions" ADD CONSTRAINT "storage_transactions_uploaded_by_fkey"
      FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'invoice_attachments' AND column_name = 'uploaded_by') THEN
    ALTER TABLE "invoice_attachments" DROP CONSTRAINT IF EXISTS "invoice_attachments_uploaded_by_fkey";
    ALTER TABLE "invoice_attachments" ADD CONSTRAINT "invoice_attachments_uploaded_by_fkey"
      FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
